export const POKEMON_TYPES = [
    "Normal", "Fire", "Water", "Grass", "Electric", "Ice", "Fighting", "Poison", "Ground",
    "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Steel", "Dark", "Fairy"
];

export const POKEMON_DATA = {
    "SPRIGATITO": { name: "Sprigatito", types: ["Grass"], image_path: "Front/SPRIGATITO.png" },
    "FLORAGATO": { name: "Floragato", types: ["Grass"], image_path: "Front/FLORAGATO.png" },
    "MEOWSCARADA": { name: "Meowscarada", types: ["Grass", "Dark"], image_path: "Front/MEOWSCARADA.png" },
    "FUECOCO": { name: "Fuecoco", types: ["Fire"], image_path: "Front/FUECOCO.png" },
    "CROCALOR": { name: "Crocalor", types: ["Fire"], image_path: "Front/CROCALOR.png" },
    "SKELEDIRGE": { name: "Skeledirge", types: ["Fire", "Ghost"], image_path: "Front/SKELEDIRGE.png" },
    "QUAXLY": { name: "Quaxly", types: ["Water"], image_path: "Front/QUAXLY.png" },
    "QUAXWELL": { name: "Quaxwell", types: ["Water"], image_path: "Front/QUAXWELL.png" },
    "QUAQUAVAL": { name: "Quaquaval", types: ["Water", "Fighting"], image_path: "Front/QUAQUAVAL.png" },
    "LECHONK": { name: "Lechonk", types: ["Normal"], image_path: "Front/LECHONK.png" },
    "OINKOLOGNE": { name: "Oinkologne", types: ["Normal"], image_path: "Front/OINKOLOGNE.png" },
    "TAROUNTULA": { name: "Tarountula", types: ["Bug"], image_path: "Front/TAROUNTULA.png" },
    "SPIDOPS": { name: "Spidops", types: ["Bug"], image_path: "Front/SPIDOPS.png" },
    "NYMBLE": { name: "Nymble", types: ["Bug"], image_path: "Front/NYMBLE.png" },
    "LOKIX": { name: "Lokix", types: ["Bug", "Dark"], image_path: "Front/LOKIX.png" },
    "PAWMI": { name: "Pawmi", types: ["Electric"], image_path: "Front/PAWMI.png" },
    "PAWMO": { name: "Pawmo", types: ["Electric", "Fighting"], image_path: "Front/PAWMO.png" },
    "PAWMOT": { name: "Pawmot", types: ["Electric", "Fighting"], image_path: "Front/PAWMOT.png" },
    "TANDEMAUS": { name: "Tandemaus", types: ["Normal"], image_path: "Front/TANDEMAUS.png" },
    "MAUSHOLD": { name: "Maushold", types: ["Normal"], image_path: "Front/MAUSHOLD.png" },
    "FIDOUGH": { name: "Fidough", types: ["Fairy"], image_path: "Front/FIDOUGH.png" },
    "DACHSBUN": { name: "Dachsbun", types: ["Fairy"], image_path: "Front/DACHSBUN.png" },
    "SMOLIV": { name: "Smoliv", types: ["Grass", "Normal"], image_path: "Front/SMOLIV.png" },
    "DOLLIV": { name: "Dolliv", types: ["Grass", "Normal"], image_path: "Front/DOLLIV.png" },
    "ARBOLIVA": { name: "Arboliva", types: ["Grass", "Normal"], image_path: "Front/ARBOLIVA.png" },
    "SQUAWKABILLY": { name: "Squawkabilly", types: ["Normal", "Flying"], image_path: "Front/SQUAWKABILLY.png" },
    "NACLI": { name: "Nacli", types: ["Rock"], image_path: "Front/NACLI.png" },
    "NACLSTACK": { name: "Naclstack", types: ["Rock"], image_path: "Front/NACLSTACK.png" },
    "GARGANACL": { name: "Garganacl", types: ["Rock"], image_path: "Front/GARGANACL.png" },
    "CHARCADET": { name: "Charcadet", types: ["Fire"], image_path: "Front/CHARCADET.png" },
    "ARMAROUGE": { name: "Armarouge", types: ["Fire", "Psychic"], image_path: "Front/ARMAROUGE.png" },
    "CERULEDGE": { name: "Ceruledge", types: ["Fire", "Ghost"], image_path: "Front/CERULEDGE.png" },
    "TADBULB": { name: "Tadbulb", types: ["Electric"], image_path: "Front/TADBULB.png" },
    "BELLIBOLT": { name: "Bellibolt", types: ["Electric"], image_path: "Front/BELLIBOLT.png" },
    "WATTREL": { name: "Wattrel", types: ["Electric", "Flying"], image_path: "Front/WATTREL.png" },
    "KILOWATTREL": { name: "Kilowattrel", types: ["Electric", "Flying"], image_path: "Front/KILOWATTREL.png" },
    "MASCHIFF": { name: "Maschiff", types: ["Dark"], image_path: "Front/MASCHIFF.png" },
    "MABOSSTIFF": { name: "Mabosstiff", types: ["Dark"], image_path: "Front/MABOSSTIFF.png" },
    "SHROODLE": { name: "Shroodle", types: ["Poison", "Normal"], image_path: "Front/SHROODLE.png" },
    "GRAFAIAI": { name: "Grafaiai", types: ["Poison", "Normal"], image_path: "Front/GRAFAIAI.png" },
    "BRAMBLIN": { name: "Bramblin", types: ["Grass", "Ghost"], image_path: "Front/BRAMBLIN.png" },
    "BRAMBLEGHAST": { name: "Brambleghast", types: ["Grass", "Ghost"], image_path: "Front/BRAMBLEGHAST.png" },
    "TOEDSCOOL": { name: "Toedscool", types: ["Ground", "Grass"], image_path: "Front/TOEDSCOOL.png" },
    "TOEDSCRUEL": { name: "Toedscruel", types: ["Ground", "Grass"], image_path: "Front/TOEDSCRUEL.png" },
    "KLAWF": { name: "Klawf", types: ["Rock"], image_path: "Front/KLAWF.png" },
    "CAPSAKID": { name: "Capsakid", types: ["Grass"], image_path: "Front/CAPSAKID.png" },
    "SCOVILLAIN": { name: "Scovillain", types: ["Grass", "Fire"], image_path: "Front/SCOVILLAIN.png" },
    "RELLOR": { name: "Rellor", types: ["Bug"], image_path: "Front/RELLOR.png" },
    "RABSCA": { name: "Rabsca", types: ["Bug", "Psychic"], image_path: "Front/RABSCA.png" },
    "FLITTLE": { name: "Flittle", types: ["Psychic"], image_path: "Front/FLITTLE.png" },
    "ESPATHRA": { name: "Espathra", types: ["Psychic"], image_path: "Front/ESPATHRA.png" },
    "TINKATINK": { name: "Tinkatink", types: ["Fairy", "Steel"], image_path: "Front/TINKATINK.png" },
    "TINKATUFF": { name: "Tinkatuff", types: ["Fairy", "Steel"], image_path: "Front/TINKATUFF.png" },
    "TINKATON": { name: "Tinkaton", types: ["Fairy", "Steel"], image_path: "Front/TINKATON.png" },
    "WIGLETT": { name: "Wiglett", types: ["Water"], image_path: "Front/WIGLETT.png" },
    "WUGTRIO": { name: "Wugtrio", types: ["Water"], image_path: "Front/WUGTRIO.png" },
    "BOMBIRDIER": { name: "Bombirdier", types: ["Flying", "Dark"], image_path: "Front/BOMBIRDIER.png" },
    "FINIZEN": { name: "Finizen", types: ["Water"], image_path: "Front/FINIZEN.png" },
    "PALAFIN": { name: "Palafin", types: ["Water"], image_path: "Front/PALAFIN.png" },
    "VAROOM": { name: "Varoom", types: ["Steel", "Poison"], image_path: "Front/VAROOM.png" },
    "REVAVROOM": { name: "Revavroom", types: ["Steel", "Poison"], image_path: "Front/REVAVROOM.png" },
    "CYCLIZAR": { name: "Cyclizar", types: ["Dragon", "Normal"], image_path: "Front/CYCLIZAR.png" },
    "ORTHWORM": { name: "Orthworm", types: ["Steel"], image_path: "Front/ORTHWORM.png" },
    "GLIMMET": { name: "Glimmet", types: ["Rock", "Poison"], image_path: "Front/GLIMMET.png" },
    "GLIMMORA": { name: "Glimmora", types: ["Rock", "Poison"], image_path: "Front/GLIMMORA.png" },
    "GREAVARD": { name: "Greavard", types: ["Ghost"], image_path: "Front/GREAVARD.png" },
    "HOUNDSTONE": { name: "Houndstone", types: ["Ghost"], image_path: "Front/HOUNDSTONE.png" },
    "FLAMIGO": { name: "Flamigo", types: ["Flying", "Fighting"], image_path: "Front/FLAMIGO.png" },
    "CETODDLE": { name: "Cetoddle", types: ["Ice"], image_path: "Front/CETODDLE.png" },
    "CETITAN": { name: "Cetitan", types: ["Ice"], image_path: "Front/CETITAN.png" },
    "VELUZA": { name: "Veluza", types: ["Water", "Psychic"], image_path: "Front/VELUZA.png" },
    "DONDOZO": { name: "Dondozo", types: ["Water"], image_path: "Front/DONDOZO.png" },
    "TATSUGIRI": { name: "Tatsugiri", types: ["Dragon", "Water"], image_path: "Front/TATSUGIRI.png" },
    "ANNIHILAPE": { name: "Annihilape", types: ["Fighting", "Ghost"], image_path: "Front/ANNIHILAPE.png" },
    "CLODSIRE": { name: "Clodsire", types: ["Poison", "Ground"], image_path: "Front/CLODSIRE.png" },
    "FARIGIRAF": { name: "Farigiraf", types: ["Normal", "Psychic"], image_path: "Front/FARIGIRAF.png" },
    "DUDUNSPARCE": { name: "Dudunsparce", types: ["Normal"], image_path: "Front/DUDUNSPARCE.png" },
    "KINGAMBIT": { name: "Kingambit", types: ["Dark", "Steel"], image_path: "Front/KINGAMBIT.png" },
    "GREATTUSK": { name: "Great Tusk", types: ["Ground", "Fighting"], image_path: "Front/GREATTUSK.png" },
    "SCREAMTAIL": { name: "Scream Tail", types: ["Fairy", "Psychic"], image_path: "Front/SCREAMTAIL.png" },
    "BRUTEBONNET": { name: "Brute Bonnet", types: ["Grass", "Dark"], image_path: "Front/BRUTEBONNET.png" },
    "FLUTTERMANE": { name: "Flutter Mane", types: ["Ghost", "Fairy"], image_path: "Front/FLUTTERMANE.png" },
    "SLITHERWING": { name: "Slither Wing", types: ["Bug", "Fighting"], image_path: "Front/SLITHERWING.png" },
    "SANDYSHOCKS": { name: "Sandy Shocks", types: ["Electric", "Ground"], image_path: "Front/SANDYSHOCKS.png" },
    "IRONTHREADS": { name: "Iron Treads", types: ["Ground", "Steel"], image_path: "Front/IRONTHREADS.png" },
    "IRONMOTH": { name: "Iron Moth", types: ["Fire", "Poison"], image_path: "Front/IRONMOTH.png" },
    "IRONHANDS": { name: "Iron Hands", types: ["Fighting", "Electric"], image_path: "Front/IRONHANDS.png" },
    "IRONJUGULIS": { name: "Iron Jugulis", types: ["Dark", "Flying"], image_path: "Front/IRONJUGULIS.png" },
    "IRONTHORNS": { name: "Iron Thorns", types: ["Rock", "Electric"], image_path: "Front/IRONTHORNS.png" },
    "IRONBUNDLE": { name: "Iron Bundle", types: ["Ice", "Water"], image_path: "Front/IRONBUNDLE.png" },
    "IRONVALIANT": { name: "Iron Valiant", types: ["Fairy", "Fighting"], image_path: "Front/IRONVALIANT.png" },
    "TINGLU": { name: "Ting-Lu", types: ["Dark", "Ground"], image_path: "Front/TINGLU.png" },
    "CHIENPAO": { name: "Chien-Pao", types: ["Dark", "Ice"], image_path: "Front/CHIENPAO.png" },
    "WOCHIEN": { name: "Wo-Chien", types: ["Dark", "Grass"], image_path: "Front/WOCHIEN.png" },
    "CHIYU": { name: "Chi-Yu", types: ["Dark", "Fire"], image_path: "Front/CHIYU.png" },
    "ROARINGMOON": { name: "Roaring Moon", types: ["Dragon", "Dark"], image_path: "Front/ROARINGMOON.png" },
    "IRONLEAVES": { name: "Iron Leaves", types: ["Grass", "Psychic"], image_path: "Front/IRONLEAVES.png" },
    "WALKINGWAKE": { name: "Walking Wake", types: ["Water", "Dragon"], image_path: "Front/WALKINGWAKE.png" },
    "KORAIDON": { name: "Koraidon", types: ["Fighting", "Dragon"], image_path: "Front/KORAIDON.png" },
    "MIRAIDON": { name: "Miraidon", types: ["Electric", "Dragon"], image_path: "Front/MIRAIDON.png" },
    "OKIDOGI": { name: "Okidogi", types: ["Poison", "Fighting"], image_path: "Front/OKIDOGI.png" },
    "MUNKIDORI": { name: "Munkidori", types: ["Poison", "Psychic"], image_path: "Front/MUNKIDORI.png" },
    "FEZANDIPITI": { name: "Fezandipiti", types: ["Poison", "Fairy"], image_path: "Front/FEZANDIPITI.png" },
    "OGERPON": { name: "Ogerpon", types: ["Grass"], image_path: "Front/OGERPON.png" },
    "ARCHALUDON": { name: "Archaludon", types: ["Steel", "Dragon"], image_path: "Front/ARCHALUDON.png" },
    "HYDRAPPLE": { name: "Hydrapple", types: ["Grass", "Dragon"], image_path: "Front/HYDRAPPLE.png" },
    "GOUGINGFIRE": { name: "Gouging Fire", types: ["Fire", "Dragon"], image_path: "Front/GOUGINGFIRE.png" },
    "RAGINGBOLT": { name: "Raging Bolt", types: ["Electric", "Dragon"], image_path: "Front/RAGINGBOLT.png" },
    "IRONBOULDER": { name: "Iron Boulder", types: ["Rock", "Psychic"], image_path: "Front/IRONBOULDER.png" },
    "IRONCROWN": { name: "Iron Crown", types: ["Steel", "Psychic"], image_path: "Front/IRONCROWN.png" },
    "TERAPAGOS": { name: "Terapagos", types: ["Normal"], image_path: "Front/TERAPAGOS.png" },
    "PECHARUNT": { name: "Pecharunt", types: ["Poison", "Ghost"], image_path: "Front/PECHARUNT.png" }
};
